### PR TITLE
Revamp materials table

### PR DESCRIPTION
**Pull request by misterjame**

### CODE REVIEW

**Review by merc1er — CHANGES_REQUESTED** [review]
Great work overall, thanks!

I see a couple minor issues:
- iron and gold images are changed, why is that?
- the corners here should be rounded (I think it is overflowing)
Screenshot 2022-05-15 at 00 45 50
- error message text color does not contrast properly with background (should be lighter)
Screenshot 2022-05-15 at 00 46 15
- inputs background is too light for the dark background (contrast issue)

**Comment by merc1er** [comment]
I can have a look at those tomorrow if you prefer @misterjame

**Comment by misterjame** [comment]
Gold and iron image dimensions were changed because the other images had more transparent space around them and it became noticeable with the alternating row color.

I'll let you take a look at these issues. Hopefully it can be completed before mooncraft

**Review by merc1er — APPROVED** [review]
Beautiful.

**Pull request merged**
