### PR TITLE
converted everything to exosama network

### PR DESCRIPTION
**Pull request by michaelRAMAGE**
I just updated things. It can be cleaned up a bit as I did it really fast.

### CODE REVIEW

**Review by merc1er — CHANGES_REQUESTED** [review]
It seems like every file was updated (different encoding?).  
Please use LF/Unix type files and leave permissions as they currently are in master.

**Comment by michaelRAMAGE** [comment]
> It seems like every file was updated (different encoding?). Please use LF/Unix type files and leave permissions as they currently are in master.

I added axios. Added a new js file called queryprices.js (some queries for khaosexchange dex subgraph that I planned on using). Changed all the movrs to sama. Added images for the new beta rss. Changed to the new subgraph and supplied the new erc1155 for beta rss and their token ids. I updated the index.html as needed (function name changes).

**Comment by michaelRAMAGE** [comment]
> > It seems like every file was updated (different encoding?). Please use LF/Unix type files and leave permissions as they currently are in master.
> 
> I am not so sure what you mean. I added axios. Added a new js file called queryprices.js (some queries for khaosexchange dex subgraph that I planned on using). Changed all the movrs to sama. Added images for the new beta rss. Changed to the new subgraph and supplied the new erc1155 for beta rss and their token ids. I updated the index.html as needed (function name changes).



> LF/Unix type files

I see. Not all are LF. I will work on that.

**Comment by merc1er** [comment]
image

Look at the diff. 33 files changed while only a couple should change.

**Comment by michaelRAMAGE** [comment]
> image
> 
> Look at the diff. 33 files changed while only a couple should change.

I noticed that github shows the file perms. I use WSL on windows so t

> image
> 
> Look at the diff. 33 files changed while only a couple should change.

I guess wsl abides to windows def file perms (777). I changed them to what they are in master (644). Git was staging with the executable bit on (git only tracks the executable bit in terms of perms). The diff seems to be correct now as it shows only the things that I actually changed, as opposed to the perm and encoding changes.

**Comment by merc1er** [comment]
@misterjame a PR for you if you're interested :)

**Comment by michaelRAMAGE** [comment]
> @misterjame a PR for you if you're interested :)

I have another to push as well but been holding off till this was resolved. Gonna commit that one...with correct perms lol

**Comment by misterjame** [comment]
The big issue with the PR is that it is not backwards compatible with alpha resources (MOVR), so it will break the calculator for all old games. Additionally, Fish are still on MOVR, so we still need MOVR prices even for current games. Also, please remove the image backgrounds when adding them to the repo. Thank you for resizing to 128x128.

Please see the changes that I've made. I've given resources a chain id and use the game date to determine if gold, etc is an alpha resource (MOVR) or beta resource (SAMA). 

**Unfortunately, I now have to leave this project, so you are welcome to work with @merc1er to continue. Here's what needs to be done:**

Fetch the MOVR/USD and SAMA/USD prices. Dailysama.com has given us permission to use `https://api.dailysama.com/utils/dailysama-tickers` to fetch the MOVR price but the origin header will not allow us to do it client side. I would suggest asking them to change the header or making a simple free Vercel app accomplish this. If you are going to use Khaos exchange data for Sama pricing, you probably should eventually ask them for permission. Also adding credit to Khaos and dailysama for the price quotes. I would limit Khaos usage to just SAMA/USD and use the moonsama marketplace order book for the resource pairs (already completed). Axios is just a wrapper for fetch when used on the client-side we are trying to keep dependencies at a bare minimum, so please use fetch.

**Comment by michaelRAMAGE** [comment]
> The big issue with the PR is that it is not backwards compatible with alpha resources (MOVR), so it will break the calculator for all old games. Additionally, Fish are still on MOVR, so we still need MOVR prices even for current games. Also, please remove the image backgrounds when adding them to the repo. Thank you for resizing to 128x128.
> 
> Please see the changes that I've made. I've given resources a chain id and use the game date to determine if gold, etc is an alpha resource (MOVR) or beta resource (SAMA).
> 
> **Unfortunately, I now have to leave this project, so you are welcome to work with @merc1er to continue. Here's what needs to be done:**
> 
> Fetch the MOVR/USD and SAMA/USD prices. Dailysama.com has given us permission to use `https://api.dailysama.com/utils/dailysama-tickers` to fetch the MOVR price but the origin header will not allow us to do it client side. I would suggest asking them to change the header or making a simple free Vercel app accomplish this. If you are going to use Khaos exchange data for Sama pricing, you probably should eventually ask them for permission. Also adding credit to Khaos and dailysama for the price quotes. I would limit Khaos usage to just SAMA/USD and use the moonsama marketplace order book for the resource pairs (already completed). Axios is just a wrapper for fetch when used on the client-side we are trying to keep dependencies at a bare minimum, so please use fetch.

Yeah, I completely ignored backwards-compatability. I am going to look a bit deeper into what you submitted soon so that I can minimize conflicts. I did already integrate Khaos Exchange successfully; I just added another column for now that shows the sama price for assets via RSS/SAMA pairs and then get SAMA/USDC for price. Another thing that I did (not comitted but in my working tree) is get the value of user resources as if they are immediately liquidating them on moonsama.marketplace.com; I take wood quantity (for instance) and fill orders until their quantity is 0 and look at that value as the total price in sama. I will move everything that I did with Khaos to fetch as well. 

Thanks for making the pull request before I got too far and also for looking at some of the code I wrote.

**Comment by misterjame** [comment]
Going to close this PR. @michaelRAMAGE you can create a new PR that fetches SAMA and MOVR prices using `fetch`. And with that, I'm leaving this project. Good luck.

**Pull request closed without merging**
